import { NextResponse } from "next/server";
import { z } from "zod";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { createSupabaseServerClient } from "@/lib/supabase/server";
export const runtime="nodejs";
async function staff(){const supabase=await createSupabaseServerClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return null;const {data:p}=await supabase.from("profiles").select("role").eq("id",user.id).maybeSingle();return p?.role==="moderator"||p?.role==="admin"?user:null;}
const schema=z.discriminatedUnion("kind",[z.object({kind:z.literal("season"),slug:z.string().regex(/^[a-z0-9-]+$/),title:z.string().min(3).max(100),startsAt:z.string().datetime(),endsAt:z.string().datetime()}),z.object({kind:z.literal("challenge"),seasonId:z.string().uuid().nullable(),slug:z.string().regex(/^[a-z0-9-]+$/),title:z.string().min(3).max(120),description:z.string().min(3).max(500),goalLabel:z.string().min(3).max(80),targetValue:z.number().int().min(1).max(100000),goalKey:z.enum(["collection_saved","rift_completed","appearance_proposed"]),startsAt:z.string().datetime(),endsAt:z.string().datetime()}),z.object({kind:z.literal("boss"),slug:z.string().regex(/^[a-z0-9-]+$/),title:z.string().min(3).max(120),maxHp:z.number().int().min(100).max(100000000),startsAt:z.string().datetime(),endsAt:z.string().datetime()})]);
export async function GET(){if(!await staff())return NextResponse.json({error:"Moderador requerido."},{status:403});const a=createSupabaseAdminClient();const [seasons,challenges,audit]=await Promise.all([a.from("challenge_seasons").select("id,slug,title,status,starts_at,ends_at").order("starts_at",{ascending:false}).limit(20),a.from("challenge_definitions").select("slug,title,target_value,starts_at,ends_at,season:season_id(title)").order("starts_at",{ascending:false}).limit(20),a.from("security_audit_events").select("category,action,metadata,created_at").order("created_at",{ascending:false}).limit(30)]);return NextResponse.json({seasons:seasons.data??[],challenges:challenges.data??[],audit:audit.data??[]});}
export async function POST(req:Request){const user=await staff();if(!user)return NextResponse.json({error:"Moderador requerido."},{status:403});const input=schema.safeParse(await req.json().catch(()=>null));if(!input.success)return NextResponse.json({error:"Datos inválidos."},{status:400});const a=createSupabaseAdminClient();let error; if(input.data.kind==="season")({error}=await a.from("challenge_seasons").insert({slug:input.data.slug,title:input.data.title,starts_at:input.data.startsAt,ends_at:input.data.endsAt,status:"active"})); if(input.data.kind==="challenge")({error}=await a.from("challenge_definitions").insert({slug:input.data.slug,title:input.data.title,description:input.data.description,goal_label:input.data.goalLabel,target_value:input.data.targetValue,starts_at:input.data.startsAt,ends_at:input.data.endsAt,is_published:true,season_id:input.data.seasonId,goal_key:input.data.goalKey,created_by:user.id})); if(input.data.kind==="boss")({error}=await a.from("rift_global_boss_events").insert({slug:input.data.slug,title:input.data.title,max_hp:input.data.maxHp,current_hp:input.data.maxHp,starts_at:input.data.startsAt,ends_at:input.data.endsAt,status:"active",created_by:user.id})); if(error)return NextResponse.json({error:"No fue posible crear el recurso. Revisa slug y fechas."},{status:409});await a.from("security_audit_events").insert({user_id:user.id,category:"moderation",action:`create_${input.data.kind}`,metadata:input.data});return NextResponse.json({ok:true},{status:201});}
const lifecycleSchema=z.object({action:z.enum(["archive","end"]),resource:z.enum(["season","challenge","boss"]),id:z.string().uuid().optional(),slug:z.string().optional()});
export async function PATCH(req:Request){const user=await staff();if(!user)return NextResponse.json({error:"Moderador requerido."},{status:403});const input=lifecycleSchema.safeParse(await req.json().catch(()=>null));if(!input.success)return NextResponse.json({error:"Acción inválida."},{status:400});const a=createSupabaseAdminClient();let error;const status=input.data.resource==="season"?"ended":input.data.resource==="challenge"?null:"ended";if(input.data.resource==="season")({error}=await a.from("challenge_seasons").update({status}).eq("id",input.data.id));if(input.data.resource==="challenge")({error}=await a.from("challenge_definitions").update({is_published:false}).eq("slug",input.data.slug));if(input.data.resource==="boss")({error}=await a.from("rift_global_boss_events").update({status}).eq("slug",input.data.slug));if(error)return NextResponse.json({error:"No fue posible archivar el recurso."},{status:500});await a.from("security_audit_events").insert({user_id:user.id,category:"moderation",action:`archive_${input.data.resource}`,metadata:input.data});return NextResponse.json({ok:true});}