import { NextResponse } from "next/server";
import { z } from "zod";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { createSupabaseServerClient } from "@/lib/supabase/server";

export const runtime = "nodejs";
const updateSchema = z.object({ reportId: z.string().uuid(), status: z.enum(["approved", "rejected", "changes_requested"]), note: z.string().trim().max(800).optional() });
async function moderator() { const supabase = await createSupabaseServerClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return null; const { data: profile } = await supabase.from("profiles").select("role").eq("id", user.id).maybeSingle(); return profile?.role === "moderator" || profile?.role === "admin" ? user : null; }
export async function GET() { const user = await moderator(); if (!user) return NextResponse.json({ error: "Moderador requerido." }, { status: 403 }); const admin = createSupabaseAdminClient(); const { data, error } = await admin.from("content_reports").select("id, target_type, target_id, reason, details, created_at, reporter_id").eq("status", "pending").order("created_at"); if (error) return NextResponse.json({ error: "No fue posible cargar reportes." }, { status: 500 }); return NextResponse.json({ reports: data ?? [] }); }
export async function PATCH(request: Request) { const user = await moderator(); if (!user) return NextResponse.json({ error: "Moderador requerido." }, { status: 403 }); const input = updateSchema.safeParse(await request.json().catch(() => null)); if (!input.success) return NextResponse.json({ error: "Decisión inválida." }, { status: 400 }); const admin = createSupabaseAdminClient(); const after = { status: input.data.status, handled_by: user.id, handled_at: new Date().toISOString() }; const { data: report, error } = await admin.from("content_reports").update(after).eq("id", input.data.reportId).select("reporter_id, id").single(); if (error || !report) return NextResponse.json({ error: "No fue posible actualizar el reporte." }, { status: 500 }); await admin.from("moderation_audit_log").insert({ actor_id: user.id, entity_type: "content_report", entity_id: report.id, action: input.data.status, after_state: after, reason: input.data.note ?? null }); await admin.from("notifications").insert({ user_id: report.reporter_id, kind: "moderation", title: "Actualización de tu reporte", body: "El staff revisó el reporte que enviaste a la comunidad.", href: "/#comunidad" }); return NextResponse.json({ ok: true }); }