"use client";

import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { createSupabaseBrowserClient } from "@/lib/supabase/browser";

type Event = { id: string; slug: string; title: string; max_hp: number; current_hp: number; status: string };
type Leader = { handle: string; damage: number };

export function GlobalBossPanel() {
  const [event, setEvent] = useState<Event | null>(null); const [leaders, setLeaders] = useState<Leader[]>([]); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const eventId = event?.id;
  async function load() { const response = await fetch("/api/rift/boss"); const data = await response.json().catch(() => ({})) as { event?: Event | null; leaderboard?: Leader[]; error?: string }; if (!response.ok) { setMessage(data.error ?? "No fue posible enlazar el jefe global."); return; } setEvent(data.event ?? null); setLeaders(data.leaderboard ?? []); }
  useEffect(() => { void fetch("/api/rift/boss").then((response) => response.json().then((data) => ({ response, data }))).then(({ response, data }: { response: Response; data: { event?: Event | null; leaderboard?: Leader[]; error?: string } }) => { if (!response.ok) { setMessage(data.error ?? "No fue posible enlazar el jefe global."); return; } setEvent(data.event ?? null); setLeaders(data.leaderboard ?? []); }).catch(() => setMessage("No fue posible enlazar el jefe global.")); }, []);
  useEffect(() => { if (!eventId) return; try { const supabase = createSupabaseBrowserClient(); const channel = supabase.channel(`rift-boss:${eventId}`).on("postgres_changes", { event: "UPDATE", schema: "public", table: "rift_global_boss_events", filter: `id=eq.${eventId}` }, (payload) => setEvent(payload.new as Event)).subscribe(); return () => { void supabase.removeChannel(channel); }; } catch { return; } }, [eventId]);
  async function attack() { if (!event) return; setBusy(true); const response = await fetch(`/api/rift/boss/${event.slug}/attack`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ actionId: crypto.randomUUID() }) }); const data = await response.json().catch(() => ({})) as { damage?: number; currentHp?: number; error?: string; defeated?: boolean }; setBusy(false); if (!response.ok) { setMessage(data.error ?? "No fue posible atacar."); return; } setEvent((current) => current && data.currentHp !== undefined ? { ...current, current_hp: data.currentHp, status: data.defeated ? "defeated" : current.status } : current); setMessage(data.defeated ? "El jefe global fue estabilizado." : `Golpe sincronizado: ${data.damage} de daño.`); void load(); }
  if (!event) return null; const percent = Math.max(0, Math.round((event.current_hp / event.max_hp) * 100));
  return <aside className="mt-6 rounded-3xl border-2 border-[#fdcc48] bg-[#172539] p-5 text-white shadow-[5px_5px_0_#f36d57]"><p className="font-mono text-[10px] font-black uppercase tracking-widest text-[#fdcc48]">Evento comunitario · jefe global</p><div className="mt-2 flex flex-wrap items-end justify-between gap-3"><div><h3 className="font-mono text-xl font-black uppercase">{event.title}</h3><p className="mt-1 text-xs text-white/70">Todos los Tamers reducen la misma vida en tiempo real.</p></div><span className="font-mono text-xs font-black">{percent}% estable</span></div><div className="mt-4 h-4 overflow-hidden rounded-full border-2 border-white bg-white/10"><div className="h-full bg-[#f36d57] transition-[width] duration-700" style={{ width: `${percent}%` }} /></div><p className="mt-2 font-mono text-xs font-black">{event.current_hp.toLocaleString("es-MX")} / {event.max_hp.toLocaleString("es-MX")} HP</p><div className="mt-4 flex flex-wrap items-center gap-3"><Button disabled={busy || event.status !== "active"} onClick={() => void attack()}>{busy ? "Transmitiendo..." : "Atacar jefe global"}</Button>{leaders.length > 0 && <p className="font-mono text-[10px] text-white/70">Líder: @{leaders[0].handle} · {leaders[0].damage} daño</p>}</div>{message && <p className="mt-3 font-mono text-xs font-black text-[#fdcc48]" role="status">{message}</p>}</aside>;
}