"use client";

import Image from "next/image";
import { useState } from "react";
import { motion } from "motion/react";
import type { Digimon } from "@/features/digimon/domain/digimon";
import { resolveAttackProfile } from "@/features/digital-run/domain/digital-run";
import { AttackSequence, TimingMeter } from "@/components/digital-run/run-effects";
import { Button } from "@/components/ui/button";
import { RiftCombatFlow } from "@/components/digital-run/rift-combat-flow";

type OnlineRun = { id: string; selected_dapi_id: number; seed: string; status: "active" | "completed" | "failed"; node: number; player_hp: number; player_energy: number; enemy_hp: number; action_count: number; score: number; enemyMaxHp?: number; enemyDapiId?: number };
type Action = "pulse" | "technique" | "guard";
type CombatEvent = { action: Action; enemyDamage: number; playerDamage: number; enemyDefeated: boolean; key: number } | null;

export function OnlineRiftPanel({ run, partner, enemy, busy, message, event, onAction, onLeave }: { run: OnlineRun; partner: Digimon | null; enemy: Digimon | null; busy: boolean; message: string; event: CombatEvent; onAction: (action: Action) => void; onLeave: () => void }) {
  const [timing, setTiming] = useState(false);
  const enemyMax = Math.max(run.enemy_hp, run.enemyMaxHp ?? 1);
  const technique = partner ? resolveAttackProfile({ name: partner.name, skills: partner.skills, attribute: partner.attribute, type: partner.type }) : { name: "Técnica digital", style: "data" as const, description: "" };
  const playerHit = Boolean(event && event.playerDamage > 0);
  const phase = timing ? "charge" : busy ? "resolve" : event?.enemyDamage ? "counter" : event?.enemyDamage === 0 && event ? "impact" : "ready";
  const enemyPercent = Math.max(0, Math.round((run.enemy_hp / enemyMax) * 100));
  return <div className="relative overflow-hidden rounded-3xl border-2 border-[#172539] bg-[#172539] p-5 text-white"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-[10px] font-black uppercase tracking-widest text-[#fdcc48]">Rift diario online · servidor</p><h3 className="mt-2 font-mono text-2xl font-black uppercase">Nodo {run.node} / 5</h3></div><Button size="sm" variant="outline" onClick={onLeave}>Volver al local</Button></div><p className="mt-3 text-sm leading-6 text-white/70">Mismas señales y efectos; el servidor decide el resultado de cada turno.</p><RiftCombatFlow phase={phase} enemyName={enemy?.name ?? "Señal hostil"} node={run.node} hpPercent={enemyPercent} /><div className="relative mt-5 grid gap-4 md:grid-cols-2"><Fighter title="Tu compañero" digimon={partner} hp={run.player_hp} max={100} energy={run.player_energy} tone="player" hit={playerHit} damage={event?.playerDamage} /><Fighter title="Señal hostil" digimon={enemy} hp={run.enemy_hp} max={enemyMax} energy={null} tone="enemy" hit={Boolean(event?.enemyDamage)} damage={event?.enemyDamage} />{event && event.action !== "guard" && <AttackSequence key={event.key} attack={event.action === "technique" ? technique : { name: "Pulso digital", style: "data", description: "" }} critical={false} />}</div>{run.status === "active" ? timing ? <TimingMeter technique={technique} onResolve={() => { setTiming(false); onAction("technique"); }} onCancel={() => setTiming(false)} /> : <div className="mt-6 flex flex-wrap justify-center gap-3"><Button disabled={busy} onClick={() => onAction("pulse")}>Pulso +10 energía</Button><Button disabled={busy || run.player_energy < 30} variant="outline" onClick={() => setTiming(true)}>Técnica · 30 energía</Button><Button disabled={busy} variant="ghost" onClick={() => onAction("guard")}>Cubrirse +18 energía</Button></div> : <div className="mt-6 rounded-xl bg-[#dcebdc] p-4 text-[#172539]"><p className="font-mono text-sm font-black uppercase">{run.status === "completed" ? `Ruta completada · ${run.score} puntos` : "Ruta dispersada"}</p><p className="mt-1 text-sm">El resultado ya está registrado en el ranking diario si tu perfil es público.</p></div>}{message && <p className="mt-4 font-mono text-xs font-black text-[#fdcc48]" role="status">{message}</p>}</div>;
}
function Fighter({ title, digimon, hp, max, energy, tone, hit, damage }: { title: string; digimon: Digimon | null; hp: number; max: number; energy: number | null; tone: "player" | "enemy"; hit: boolean; damage?: number }) { const percent = Math.max(0, Math.min(100, Math.round((hp / max) * 100))); return <motion.article animate={hit ? { x: [0, -8, 7, 0], scale: [1, .98, 1] } : { x: 0, scale: 1 }} transition={{ duration: .38 }} className={`relative rounded-3xl border-2 border-white/40 p-4 ${tone === "enemy" ? "bg-[#f36d57]/85" : "bg-white/10"}`}><div className="flex items-center gap-4">{digimon?.image ? <Image src={digimon.image} alt={digimon.name} width={78} height={78} unoptimized className="size-16 object-contain" /> : <div className="grid size-16 place-items-center rounded-xl bg-white/15 font-mono text-[9px]">SCAN</div>}<div className="min-w-0"><p className="font-mono text-[10px] font-black uppercase text-white/70">{title}</p><h4 className="truncate font-mono text-lg font-black uppercase">{digimon?.name ?? "Señal hostil"}</h4><p className="font-mono text-xs text-white/75">{digimon ? `${digimon.level} · ${digimon.attribute}` : "Rift core"}</p></div></div>{damage ? <span className="run-damage-float absolute right-5 top-4 font-mono text-xl font-black text-[#fdcc48]">-{damage}</span> : null}<Bar label="HP" value={`${hp}/${max}`} percent={percent} color={tone === "enemy" ? "bg-[#d85746]" : "bg-[#79c8ea]"} />{energy !== null && <Bar label="Energía" value={`${energy}/100`} percent={energy} color="bg-[#fdcc48]" />}</motion.article>; }
function Bar({ label, value, percent, color }: { label: string; value: string; percent: number; color: string }) { return <div className="mt-3"><div className="mb-1 flex justify-between font-mono text-[9px] font-black"><span>{label}</span><span>{value}</span></div><div className="h-3 overflow-hidden rounded-full border-2 border-white bg-white/15"><div className={`h-full transition-[width] duration-500 ${color}`} style={{ width: `${percent}%` }} /></div></div>; }