"use client";

import type { Digimon } from "@/features/digimon/domain/digimon";
import { Button } from "@/components/ui/button";

type OnlineRun = { id: string; selected_dapi_id: number; seed: string; status: "active" | "completed" | "failed"; node: number; player_hp: number; player_energy: number; enemy_hp: number; action_count: number; score: number; enemyMaxHp?: number };
type Action = "pulse" | "technique" | "guard";

export function OnlineRiftPanel({ run, partner, busy, message, onAction, onLeave }: { run: OnlineRun; partner: Digimon | null; busy: boolean; message: string; onAction: (action: Action) => void; onLeave: () => void }) {
  const enemyMax = Math.max(run.enemy_hp, run.enemyMaxHp ?? 1);
  return <div className="rounded-3xl border-2 border-[#172539] bg-[#172539] p-5 text-white"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-[10px] font-black uppercase tracking-widest text-[#fdcc48]">Rift diario online · servidor</p><h3 className="mt-2 font-mono text-2xl font-black uppercase">Nodo {run.node} / 5</h3></div><Button size="sm" variant="outline" onClick={onLeave}>Volver al local</Button></div><p className="mt-4 text-sm leading-6 text-white/70">El servidor valida cada turno. Los multiplicadores visuales del minijuego local no alteran esta ruta competitiva.</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><Status title={partner?.name ?? "Tu compañero"} value={run.player_hp} max={100} color="bg-[#79c8ea]" caption={`Energía ${run.player_energy}/100`} /><Status title="Señal hostil" value={run.enemy_hp} max={enemyMax} color="bg-[#f36d57]" caption={`Acciones ${run.action_count}`} /></div>{run.status === "active" ? <div className="mt-6 flex flex-wrap gap-3"><Button disabled={busy} onClick={() => onAction("pulse")}>Pulso</Button><Button disabled={busy || run.player_energy < 30} variant="outline" onClick={() => onAction("technique")}>Técnica · 30 energía</Button><Button disabled={busy} variant="ghost" onClick={() => onAction("guard")}>Cubrirse</Button></div> : <div className="mt-6 rounded-xl bg-[#dcebdc] p-4 text-[#172539]"><p className="font-mono text-sm font-black uppercase">{run.status === "completed" ? `Ruta completada · ${run.score} puntos` : "Ruta dispersada"}</p><p className="mt-1 text-sm">El resultado ya está registrado en el ranking diario si tu perfil es público.</p></div>}{message && <p className="mt-4 font-mono text-xs font-black text-[#fdcc48]" role="status">{message}</p>}</div>;
}
function Status({ title, value, max, color, caption }: { title: string; value: number; max: number; color: string; caption: string }) { const percent = Math.max(0, Math.min(100, Math.round((value / max) * 100))); return <div className="rounded-2xl border-2 border-white/30 p-4"><p className="font-mono text-[10px] font-black uppercase text-white/65">{title}</p><div className="mt-3 h-3 overflow-hidden rounded-full border border-white bg-white/10"><div className={`h-full transition-[width] duration-500 ${color}`} style={{ width: `${percent}%` }} /></div><p className="mt-2 font-mono text-xs font-black">HP {value}/{max} · {caption}</p></div>; }