"use client";

import { useEffect, useState } from "react";
import { InfoHint } from "@/components/ui/info-hint";

type Challenge = { id: string; slug: string; title: string; description: string; goal_label: string; target_value: number; ends_at: string };
type Progress = { challenge_id: string; progress_value: number; completed_at: string | null };
type Leader = { handle: string; progressValue: number; completedAt: string | null };

export function ChallengeBoard() {
  const [challenges, setChallenges] = useState<Challenge[]>([]);
  const [progress, setProgress] = useState<Progress[]>([]);
  const [leaders, setLeaders] = useState<Record<string, Leader[]>>({});
  const [message, setMessage] = useState("Cargando retos...");

  useEffect(() => { void fetch("/api/challenges").then((response) => response.json().then((data) => ({ response, data }))).then(({ response, data }: { response: Response; data: { challenges?: Challenge[]; progress?: Progress[]; leaderboards?: Record<string, Leader[]>; error?: string } }) => { if (!response.ok) { setMessage(data.error ?? "No fue posible cargar los retos."); return; } setChallenges(data.challenges ?? []); setProgress(data.progress ?? []); setLeaders(data.leaderboards ?? {}); setMessage(data.challenges?.length ? "" : "No hay retos activos todavía."); }).catch(() => setMessage("No fue posible cargar los retos.")); }, []);

  return <section id="retos" className="border-y-2 border-[#172539] bg-[#fdcc48]"><div className="mx-auto max-w-7xl px-5 py-14 lg:px-8"><p className="font-mono text-xs font-black uppercase tracking-[0.16em]">Retos de Tamer</p><div className="mt-4 flex items-start gap-3"><h2 className="font-mono text-3xl font-black uppercase leading-none tracking-[-0.07em] sm:text-5xl">Misiones y señales destacadas.</h2><InfoHint className="mt-1" text="El progreso se registra al realizar acciones compatibles, por ejemplo guardar una nueva señal. Los rankings sólo muestran perfiles públicos." /></div><p className="mt-4 max-w-2xl text-sm leading-6 text-[#405065]">Completa objetivos desde el portal y compara tu avance con Tamers que decidieron mostrar su perfil.</p>{message && <p className="mt-6 rounded-xl border-2 border-[#172539] bg-[#f7f1e7] p-3 font-mono text-xs font-bold" role="status">{message}</p>}<div className="mt-7 grid gap-5 lg:grid-cols-2">{challenges.map((challenge) => { const own = progress.find((item) => item.challenge_id === challenge.id); const amount = own?.progress_value ?? 0; const percent = Math.min(100, Math.round((amount / challenge.target_value) * 100)); return <article key={challenge.id} className="rounded-3xl border-2 border-[#172539] bg-[#f7f1e7] p-6 shadow-[5px_5px_0_#172539]"><div className="flex items-start justify-between gap-4"><div><h3 className="font-mono text-2xl font-black uppercase leading-none">{challenge.title}</h3><p className="mt-3 text-sm leading-6 text-[#405065]">{challenge.description}</p></div><span className="rounded-full border-2 border-[#172539] bg-[#dcebdc] px-3 py-1 font-mono text-[10px] font-black uppercase">{percent}%</span></div><div className="mt-5"><div className="h-3 overflow-hidden rounded-full border-2 border-[#172539] bg-white"><div className="h-full bg-[#f36d57] transition-[width] duration-700" style={{ width: `${percent}%` }} /></div><p className="mt-2 font-mono text-xs font-black uppercase">{amount} / {challenge.target_value} {challenge.goal_label}</p></div><div className="mt-6 border-t-2 border-[#172539]/20 pt-4"><p className="font-mono text-[10px] font-black uppercase tracking-widest">Ranking público</p><ol className="mt-2 space-y-1 text-sm">{(leaders[challenge.id] ?? []).length ? (leaders[challenge.id] ?? []).map((leader, index) => <li key={`${leader.handle}-${index}`} className="flex justify-between"><span>#{index + 1} @{leader.handle}</span><strong>{leader.progressValue}</strong></li>) : <li className="text-[#405065]">Aún no hay perfiles públicos clasificados.</li>}</ol></div></article>; })}</div></div></section>;
}